apiVersion: v1
kind: ConfigMap
metadata:
  name: smartnotes-config
  namespace: smartnotes
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Aws__Region: "us-east-1"
  Aws__SqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/679336465006/smartnotes-processing-mannan"
  Aws__SnsTopicArn: "arn:aws:sns:us-east-1:679336465006:smartnotes-events-mannan"
  Aws__S3BucketName: "smartnotes-attachments-mannan"
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_NAME: "smartnotes_db"
