<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SmartNotes.Worker-83a1e1a6-8197-467b-8826-f6209ec45a5d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.2.35" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.33" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartNotes.Core\SmartNotes.Core.csproj" />
    <ProjectReference Include="..\SmartNotes.Api\SmartNotes.Api.csproj" />
  </ItemGroup>

</Project>